## 什么是 NumPy?

NumPy是Python中科学计算的基础包。它是一个Python库，提供多维数组对象，各种派生对象（如掩码数组和矩阵），以及用于数组快速操作的各种API，有包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数，基本统计运算和随机模拟等等。

NumPy包的核心是 ndarray 对象。它封装了python原生的同数据类型的 n 维数组，为了保证其性能优良，其中有许多操作都是代码在本地进行编译后执行的。

NumPy数组 和 原生Python Array（数组）之间有几个重要的区别：

1. NumPy 数组在创建时具有固定的大小，与Python的原生数组对象（可以动态增长）不同。更改ndarray的大小将创建一个新数组并删除原来的数组。

2. NumPy 数组中的元素都需要具有相同的数据类型，因此在内存中的大小相同。 例外情况：Python的原生数组里包含了NumPy的对象的时候，这种情况下就允许不同大小元素的数组。

3. NumPy 数组有助于对大量数据进行高级数学和其他类型的操作。通常，这些操作的执行效率更高，比使用Python原生数组的代码更少。

4. 越来越多的基于Python的科学和数学软件包使用NumPy数组; 虽然这些工具通常都支持Python的原生数组作为参数，但它们在处理之前会还是会将输入的数组转换为NumPy的数组，而且也通常输出为NumPy数组。换句话说，为了高效地使用当今科学/数学基于Python的工具（大部分的科学计算工具），你只知道如何使用Python的原生数组类型是不够的 - 还需要知道如何使用 NumPy 数组。

# 为什么 NumPy 这么快？

**矢量化**描述了代码中没有任何显式的循环，索引等 - 这些当然是预编译的C代码中“幕后”优化的结果。矢量化代码有许多优点，其中包括：

1. 矢量化代码更简洁，更易于阅读
2. 更少的代码行通常意味着更少的错误
3. 代码更接近于标准的数学符号（通常，更容易正确编码数学结构）
4. 矢量化导致产生更多 “Pythonic” 代码。如果没有矢量化，**我们的代码就会被低效且难以阅读的for循环所困扰**。

**广播**是用于描述操作的隐式逐元素行为的术语; 一般来说，在NumPy中，所有操作，不仅仅是算术运算，而是逻辑，位，功能等，都以这种隐式的逐元素方式表现，即它们进行广播。此外，在上面的例子中，a并且b可以是相同形状的多维数组，或者标量和数组，或者甚至是具有不同形状的两个数组，条件是较小的数组可以“扩展”到更大的形状。结果广播明确无误的方式。有关广播的详细“规则”，请参阅numpy.doc.broadcasting。

# 基础知识

NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。

例如，3D空间中的点的坐标[1, 2, 1]具有一个轴。该轴有3个元素，所以我们说它的长度为3.在下图所示的例子中，数组有2个轴。第一轴的长度为2，第二轴的长度为3。

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

NumPy的数组类被调用**ndarray**。它也被别名所知 **array**。请注意，numpy.array这与标准Python库类不同array.array，后者只处理一维数组并提供较少的功能。ndarray对象更重要的属性是：

1. **ndarray.ndim** - 数组的轴（维度）的个数。在Python世界中，维度的数量被称为rank。
2. **ndarray.shape** - 数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。因此，shape 元组的长度就是rank或维度的个数 ndim。
3. **ndarray.size** - 数组元素的总数。这等于 shape 的元素的乘积。
4. **ndarray.dtype** - 一个描述数组中元素类型的对象。可以使用标准的Python类型创建或指定dtype。另外NumPy提供它自己的类型。例如numpy.int32、numpy.int16和numpy.float64。
5. **ndarray.itemsize** - 数组中每个元素的字节大小。例如，元素为 float64 类型的数组的 itemsize 为8（=64/8），而 complex32 类型的数组的 itemsize 为4（=32/8）。它等于 ndarray.dtype.itemsize 。
6. **ndarray.data** - 该缓冲区包含数组的实际元素。通常，我们不需要使用此属性，因为我们将使用索引访问数组中的元素。

# 一个例子

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

# 数组创建

有几种方法可以创建数组。
例如，你可以使用array函数从常规Python列表或元组中创建数组。得到的数组的类型是从Python列表中元素的类型推导出来的。

In [11]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

一个常见的错误，就是调用array的时候传入多个数字参数，而不是提供单个数字的列表类型作为参数。

In [15]:
# a = np.array(1,2,3,4)    # WRONG
# a = np.array([1,2,3,4])  # RIGHT

array 还可以将序列的序列转换成二维数组，将序列的序列的序列转换成三维数组，等等。

In [16]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

也可以在创建时显式指定数组的类型：

In [17]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

通常，数组的元素最初是未知的，但它的大小是已知的。因此，NumPy提供了几个函数来创建具有初始占位符内容的数组。这就减少了数组增长的必要，因为数组增长的操作花费很大。

函数zeros创建一个由0组成的数组，函数 ones创建一个完整的数组，函数empty 创建一个数组，其初始内容是随机的，取决于内存的状态。默认情况下，创建的数组的dtype是 float64 类型的。

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.empty((2,3))  

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

为了创建数字组成的数组，NumPy提供了一个类似于range的函数，该函数返回数组而不是列表。

In [27]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [28]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

当arange与浮点参数一起使用时，由于有限的浮点精度，通常不可能预测所获得的元素的数量。出于这个原因，通常最好使用linspace函数来接收我们想要的元素数量的函数，而不是步长（step）：

In [29]:
from numpy import pi
np.linspace( 0, 2, 9 )  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)

# 打印数组
当您打印数组时，NumPy以与嵌套列表类似的方式显示它，但具有以下布局：

1. 最后一个轴从左到右打印,
2. 倒数第二个从上到下打印,
3. 其余部分也从上到下打印，每个切片用空行分隔。

然后将一维数组打印为行，将二维数据打印为矩阵，将三维数据打印为矩数组表。

In [34]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [35]:
b = np.arange(12).reshape(4,3) 
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


如果数组太大而无法打印，NumPy会自动跳过数组的中心部分并仅打印角点：

In [37]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [38]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


要禁用此行为并强制NumPy打印整个数组，可以使用更改打印选项set_printoptions。

In [40]:
'''
import sys
np.set_printoptions(threshold=sys.maxsize)       # sys module should be imported
'''

'\nimport sys\nnp.set_printoptions(threshold=sys.maxsize)       # sys module should be imported\n'

# 基本操作
数组上的算术运算符会应用到 元素 级别。下面是创建一个新数组并填充结果的示例：

In [44]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [45]:
c = a - b
c

array([20, 29, 38, 47])

In [46]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [47]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [48]:
a<35

array([ True,  True, False, False])

与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行运算。矩阵乘积可以使用@运算符（在python> = 3.5中）或dot函数或方法执行：

In [49]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [50]:
A * B # [[1*2，1*0]，[0*3，1*4]]

array([[2, 0],
       [0, 4]])

In [51]:
A @ B  # （2*2） @ （2*2） = 2*2

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

某些操作（例如+=和 *=）会更直接更改被操作的矩阵数组而不会创建新矩阵数组。

In [59]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [60]:
b += a
b

array([[3.86270756, 3.67118418, 3.27435295],
       [3.39660324, 3.39843641, 3.71224354]])

In [61]:
a += b        # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

当使用不同类型的数组进行操作时，结果数组的类型对应于更一般或更精确的数组（称为向上转换的行为）。

In [62]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [65]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [66]:
c.dtype.name

'float64'

In [67]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [68]:
d.dtype.name

'complex128'

许多一元操作，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的。

In [70]:
a = np.random.random((2,3))
a

array([[0.44542941, 0.58660203, 0.40114854],
       [0.07474002, 0.48583319, 0.29708192]])

In [71]:
a.sum()

2.2908351135949374

In [72]:
a.min()

0.07474002290743553

In [74]:
a.max()

0.586602030992102

默认情况下，这些操作适用于数组，就像它是一个数字列表一样，无论其形状如何。但是，通过指定axis 参数，您可以沿数组的指定轴应用操作：

In [76]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
b.sum(axis=0)   # sum of each column

array([12, 15, 18, 21])

In [78]:
b.min(axis=1)   # min of each row

array([0, 4, 8])

In [79]:
b.cumsum(axis=1)   # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

# 通函数
NumPy提供熟悉的数学函数，例如sin，cos和exp。在NumPy中，这些被称为“通函数”（ufunc）。在NumPy中，这些函数在数组上按元素进行运算，产生一个数组作为输出。

In [81]:
B = np.arange(3)
B

array([0, 1, 2])

In [82]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [83]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [84]:
C = np.array([2., -1., 4.])

In [85]:
np.add(B, C)

array([2., 0., 6.])

另见这些通函数

all， any， apply_along_axis， argmax， argmin， argsort， average， bincount， ceil， clip， conj， corrcoef， cov， cross， cumprod， cumsum， diff， dot， floor， inner， INV ， lexsort， max， maximum， mean， median， min， minimum， nonzero， outer， prod， re， round， sort， std， sum， trace， transpose， var， vdot， vectorize， where

# 索引、切片和迭代
一维的数组可以进行索引、切片和迭代操作的，就像 列表 和其他Python序列类型一样。

In [105]:
a = np.arange(10)*3
print(a)

a = np.arange(10)**3 # n的几次幂
a

[ 0  3  6  9 12 15 18 21 24 27]


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [103]:
a[2]

8

In [88]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [108]:
 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000 
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [107]:
a[ : :-1] # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [92]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


D:\python\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


多维的数组每个轴可以有一个索引。这些索引以逗号​​分隔的元组给出：

In [95]:
def f(x,y):
    return 10*x+y

In [96]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

### 取元素 X[n0,n1]

这是最基本的情况，表示取 第0维 的第 n0 个元素，继续取 第1维 的第 n1个元素。如 X[2,2] 表示第0维第2个元素[20,21,22,23],然后取其第1维的第2个元素即 22；

### 切片 X[s0:e0,s1:e1]

这是最通用的切片操作，表示取 第0维 的第 s0 到 e0 个元素，继续取 第1维 的第 s1 到 e1 个元素（左闭右开）。如 X[1:3,1:3] 表示第0维第(1:3)个元素[[10,11,12,13],[20,21,22,23]],然后取其第1维的第(1:3)个元素即 [[11,12],[21,22]]；

In [ ]:
二维就是一个逗号，左边负责第一维度的切分，右边负责第二维度的切分

In [97]:
b[2,3] # 第一维度第二个元素，第二维度第三个元素，从0开始，01234

23

In [98]:
b[0:5, 1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [99]:
b[ : ,1] # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [109]:
b[ : 1]

array([[0, 1, 2, 3]])

In [100]:
 b[1:3, : ] # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片:

In [101]:
b[-1]   # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

b[i] 方括号中的表达式 i 被视为后面紧跟着 : 的多个实例，用于表示剩余轴。NumPy也允许你使用三个点写为 b[i,...]。

三个点（ ... ）表示产生完整索引元组所需的冒号。例如，如果 x 是rank为5的数组（即，它具有5个轴），则：

1. x[1,2,...] 相当于 x[1,2,:,:,:]，
2. x[...,3] 等效于 x[:,:,:,:,3]
3. x[4,...,5,:] 等效于 x[4,:,:,5,:]。

In [111]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
            [ 10, 12, 13]],
            [[100,101,102],
            [110,112,113]]])
c.shape

(2, 2, 3)

In [112]:
c[1,...] 

array([[100, 101, 102],
       [110, 112, 113]])

In [113]:
 c[...,2] 

array([[  2,  13],
       [102, 113]])

对多维数组进行 **迭代**（Iterating） 是相对于第一个轴完成的：

In [115]:
print(b)
for row in b:
    print(row)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


但是，如果想要对数组中的每个元素执行操作，可以使用flat属性，该属性是数组的所有元素的迭代器

In [116]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# 形状操纵

## 改变数组的形状
一个数组的形状是由每个轴的元素数量决定的：
np.floor()返回不大于输入参数的最大整数。（向下取整）

In [118]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 0., 2., 1.],
       [3., 3., 7., 5.],
       [9., 2., 8., 9.]])

In [119]:
a.shape

(3, 4)

可以使用各种命令更改数组的形状。请注意，以下三个命令都返回一个修改后的数组，但不会更改原始数组：

In [120]:
a.ravel()  # returns the array, flattened

array([8., 0., 2., 1., 3., 3., 7., 5., 9., 2., 8., 9.])

In [121]:
a.reshape(6,2)  # returns the array with a modified shape

array([[8., 0.],
       [2., 1.],
       [3., 3.],
       [7., 5.],
       [9., 2.],
       [8., 9.]])

In [122]:
a.T  # returns the array, transposed

array([[8., 3., 9.],
       [0., 3., 2.],
       [2., 7., 8.],
       [1., 5., 9.]])

In [123]:
a.T.shape

(4, 3)

In [124]:
a.shape

(3, 4)

由 ravel() 产生的数组中元素的顺序通常是“C风格”，也就是说，最右边的索引“变化最快”，因此[0,0]之后的元素是[0,1] 。如果将数组重新整形为其他形状，则该数组将被视为“C风格”。NumPy通常创建按此顺序存储的数组，因此 ravel() 通常不需要复制其参数，但如果数组是通过获取另一个数组的切片或使用不常见的选项创建的，则可能需要复制它。还可以使用可选参数指示函数 ravel() 和 reshape()，以使用FORTRAN样式的数组，其中最左边的索引变化最快。

该reshape函数返回带有修改形状的参数，而该 ndarray.resize方法会修改数组本身：

In [125]:
a

array([[8., 0., 2., 1.],
       [3., 3., 7., 5.],
       [9., 2., 8., 9.]])

In [127]:
a.resize((2,6))
a

array([[8., 0., 2., 1., 3., 3.],
       [7., 5., 9., 2., 8., 9.]])

如果在 reshape 操作中将 size 指定为-1，则会自动计算其他的 size 大小

In [128]:
a.reshape(3,-1)

array([[8., 0., 2., 1.],
       [3., 3., 7., 5.],
       [9., 2., 8., 9.]])

## 将不同数组堆叠在一起
几个数组可以沿不同的轴堆叠在一起，例如：

In [130]:
a = np.floor(10*np.random.random((2,2)))
a

array([[2., 7.],
       [1., 4.]])

In [131]:
b = np.floor(10*np.random.random((2,2)))
b

array([[8., 3.],
       [0., 8.]])

In [132]:
np.vstack((a,b))

array([[2., 7.],
       [1., 4.],
       [8., 3.],
       [0., 8.]])

In [133]:
np.hstack((a,b))

array([[2., 7., 8., 3.],
       [1., 4., 0., 8.]])

该函数将column_stack 1D数组作为列堆叠到2D数组中。它仅相当于 hstack2D数组：

In [136]:
from numpy import newaxis
np.column_stack((a,b))  # with 2D arrays

array([[2., 7., 8., 3.],
       [1., 4., 0., 8.]])

In [137]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [138]:
np.hstack((a,b)) # the result is different

array([4., 2., 3., 8.])

In [139]:
a[:,newaxis]   # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [140]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [141]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

## 注意
在复杂的情况下，r_和c c_于通过沿一个轴堆叠数字来创建数组很有用。它们允许使用范围操作符(“：”)。

In [143]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

## 将一个数组拆分成几个较小的数组
使用hsplit，可以沿数组的水平轴拆分数组，方法是指定要返回的形状相等的数组的数量，或者指定应该在其之后进行分割的列：

In [144]:
a = np.floor(10*np.random.random((2,12)))
a

array([[2., 8., 8., 4., 4., 6., 0., 0., 2., 2., 1., 9.],
       [1., 6., 7., 2., 1., 4., 7., 4., 4., 3., 7., 0.]])

In [145]:
np.hsplit(a,3)   # Split a into 3

[array([[2., 8., 8., 4.],
        [1., 6., 7., 2.]]),
 array([[4., 6., 0., 0.],
        [1., 4., 7., 4.]]),
 array([[2., 2., 1., 9.],
        [4., 3., 7., 0.]])]

In [146]:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[2., 8., 8.],
        [1., 6., 7.]]),
 array([[4.],
        [2.]]),
 array([[4., 6., 0., 0., 2., 2., 1., 9.],
        [1., 4., 7., 4., 4., 3., 7., 0.]])]

vsplit沿垂直轴分割，并array_split允许指定要分割的轴

# 拷贝和视图
当计算和操作数组时，有时会将数据复制到新数组中，有时则不会。这通常是初学者混淆的根源。有三种情况：

## 完全不复制
简单分配不会复制数组对象或其数据。

In [151]:
a = np.arange(12)
b = a            # no new object is created

In [152]:
b is a           # a and b are two names for the same ndarray object

True

In [153]:
b.shape = 3,4    # changes the shape of a

In [154]:
a.shape

(3, 4)

Python将可变对象作为引用传递，因此函数调用不会复制。

In [155]:
def f(x):
    print(id(x))

In [156]:
id(a) # id is a unique identifier of an object

3274767076608

In [157]:
f(a)

3274767076608


## 视图或浅拷贝
不同的数组对象可以共享相同的数据。该view方法创建一个查看相同数据的新数组对象。

In [158]:
c = a.view()
c is a

False

In [159]:
c.base is a                        # c is a view of the data owned by a

True

In [160]:
c.flags.owndata

False

In [161]:
c.shape = 2,6                      # a's shape doesn't change

In [162]:
a.shape

(3, 4)

In [163]:
c[0,4] = 1234 # a's data changes

In [164]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

切片数组会返回一个视图：

In [166]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## 深拷贝
该copy方法生成数组及其数据的完整副本。

In [167]:
d = a.copy()  # a new array object with new data is created
d is a

False

In [168]:
d.base is a # d doesn't share anything with a

False

In [169]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

有时，如果不再需要原始数组，则应在切片后调用 copy。例如，假设a是一个巨大的中间结果，最终结果b只包含a的一小部分，那么在用切片构造b时应该做一个深拷贝：

In [171]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

如果改为使用 b = a[:100]，则 a 由 b 引用，并且即使执行 del a 也会在内存中持久存在

## 功能和方法概述
以下是按类别排序的一些有用的NumPy函数和方法名称的列表。有关完整列表，请参阅参考手册里的常用API。

1. 数组的创建（Array Creation） - arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, zeros, zeros_like
2. 转换和变换（Conversions） - ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
3. 操纵术（Manipulations） - array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
4. 询问（Questions） - all, any, nonzero, where,
5. 顺序（Ordering） - argmax, argmin, argsort, max, min, ptp, searchsorted, sort
6. 操作（Operations） - choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
7. 基本统计（Basic Statistics） - cov, mean, std, var
8. 基本线性代数（Basic Linear Algebra） - cross, dot, outer, linalg.svd, vdot

# 广播（Broadcasting）规则
广播允许通用功能以有意义的方式处理不具有完全相同形状的输入。

广播的第一个规则是，如果所有输入数组不具有相同数量的维度，则将“1”重复地预先添加到较小数组的形状，直到所有数组具有相同数量的维度。

广播的第二个规则确保沿特定维度的大小为1的数组表现为具有沿该维度具有最大形状的数组的大小。假定数组元素的值沿着“广播”数组的那个维度是相同的。

应用广播规则后，所有数组的大小必须匹配。更多细节可以在广播中找到。

术语广播（Broadcasting）描述了 numpy 如何在算术运算期间处理具有不同形状的数组。受某些约束的影响，较小的数组在较大的数组上“广播”，以便它们具有兼容的形状。广播提供了一种矢量化数组操作的方法，以便在C而不是Python中进行循环。它可以在不制作不必要的数据副本的情况下实现这一点，通常导致高效的算法实现。然而，有些情况下广播是一个坏主意，因为它会导致内存使用效率低下，从而减慢计算速度。

NumPy 操作通常在逐个元素的基础上在数组对上完成。在最简单的情况下，两个数组必须具有完全相同的形状，如下例所示：

In [172]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

当数组的形状满足某些约束时，NumPy的广播规则放宽了这种约束。当一个数组和一个标量值在一个操作中组合时，会发生最简单的广播示例：

In [173]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

结果等同于前面的示例，其中b是数组。我们可以将在算术运算期间b被 拉伸 的标量想象成具有相同形状的数组a。新元素 b只是原始标量的副本。拉伸类比只是概念性的。NumPy足够聪明，可以使用原始标量值而无需实际制作副本，因此广播操作尽可能具有内存和计算效率。

第二个示例中的代码比第一个示例中的代码更有效，因为广播在乘法期间移动的内存较少（b是标量而不是数组）。

## 一般广播规则
在两个数组上运行时，NumPy会逐元素地比较它们的形状。它从尾随尺寸开始，并向前发展。两个尺寸兼容时

1. 他们是平等的，或者
2. 其中一个是1

如果不满足这些条件，则抛出 ValueError: operands could not be broadcast together 异常，指示数组具有不兼容的形状。结果数组的大小是沿输入的每个轴不是1的大小。

数组不需要具有相同 数量 的维度。例如，如果您有一个256x256x3RGB值数组，并且希望将图像中的每种颜色缩放不同的值，则可以将图像乘以具有3个值的一维数组。根据广播规则排列这些数组的尾轴的大小，表明它们是兼容的：

In [ ]:
# Image  (3d array): 256 x 256 x 3
# Scale  (1d array):             3
# Result (3d array): 256 x 256 x 3

当比较的任何一个尺寸为1时，使用另一个尺寸。换句话说，尺寸为1的尺寸被拉伸或“复制”以匹配另一个尺寸。

在以下示例中，A和B数组都具有长度为1的轴，在广播操作期间会扩展为更大的大小：

In [ ]:
# A      (4d array):  8 x 1 x 6 x 1
# B      (3d array):      7 x 1 x 5
# Result (4d array):  8 x 7 x 6 x 5

实践中广播的一个例子：

In [174]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

x.shape

(4,)

In [175]:
y.shape

(5,)

In [176]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [177]:
xx.shape

(4, 1)

In [178]:
y.shape

(5,)

In [179]:
(xx + y).shape

(4, 5)

In [180]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [181]:
x.shape

(4,)

In [182]:
z.shape

(3, 4)

In [183]:
(x + z).shape

(3, 4)

In [184]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

广播提供了一种方便的方式来获取两个数组的外积（或任何其他外部操作）。以下示例显示了两个1-d数组的外积操作：

In [185]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# 花式索引和索引技巧
NumPy提供比常规Python序列更多的索引功能。除了通过整数和切片进行索引之外，正如我们之前看到的，数组可以由整数数组和布尔数组索引。

## 使用索引数组进行索引

In [186]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
a[i]    

array([ 1,  1,  9, 64, 25], dtype=int32)

In [187]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j]                                       # the same shape as j

array([[ 9, 16],
       [81, 49]], dtype=int32)

当索引数组a是多维的时，单个索引数组指的是第一个维度a。以下示例通过使用调色板将标签图像转换为彩色图像来显示此行为。

In [188]:
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                      [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                     [ 0, 3, 4, 0 ]  ] )
palette[image]                            # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])