In [1]:
# 导入numpy库
import numpy as np

# ndarray运算

* **1 逻辑运算-布尔索引**


* **2 通用判断函数**
    * np.all()
    * np.any()


* **3 np.where（三元运算符）**
    * np.where()


* **4 统计运算**
    * np.max()
    * np.min()
    * ...
    
    
* **5 数组排序**
    * np.sort()
    * np.argsort()

## 1 逻辑运算-布尔索引
如果想要操作符合某一条件的数据，应该怎么操作？

假设现在有10名同学，5名功课的数据。现在想要筛选出前5名同学成绩小于60的数据，并设置为0分。

In [2]:
# 生成10名同学5名功课的数据
score = np.random.randint(40,100,(10,5))
score

array([[53, 75, 99, 91, 63],
       [58, 83, 67, 68, 69],
       [92, 66, 62, 43, 47],
       [74, 40, 66, 73, 47],
       [96, 99, 95, 90, 43],
       [86, 69, 86, 44, 51],
       [63, 51, 95, 87, 64],
       [88, 83, 76, 97, 57],
       [61, 98, 66, 40, 81],
       [74, 70, 51, 41, 73]])

In [3]:
# 提取前5名同学的成绩
test_score = score[:5,:]

# 逻辑判断
test_score < 60

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False,  True,  True],
       [False,  True, False, False,  True],
       [False, False, False, False,  True]])

In [4]:
# 布尔索引：将满足条件的值设置为0
test_score[test_score < 60] = 0
test_score

array([[ 0, 75, 99, 91, 63],
       [ 0, 83, 67, 68, 69],
       [92, 66, 62,  0,  0],
       [74,  0, 66, 73,  0],
       [96, 99, 95, 90,  0]])

## 2 通用判断函数
* np.all；验证任何一个元素是否都符合条件
* np.any：验证是否有一个元素符合条件

In [5]:
# 检验数组score里面的值是否都大于60
np.all(score > 60)

False

In [6]:
# 检验数组score里面的值是否有小于60的值
np.any(score < 60)

True

## 3 np.where（三元运算符）
通过使用np.where能够进行更加复杂的运算
* np.where(condition,[x, y])

In [7]:
# 判断前5名同学的前4门课程中，成绩中大于60的设为1，否则设为0
temp_score = score[:5, :4]
temp_score

array([[ 0, 75, 99, 91],
       [ 0, 83, 67, 68],
       [92, 66, 62,  0],
       [74,  0, 66, 73],
       [96, 99, 95, 90]])

In [8]:
# 成绩中大于60的设为1，否则设为0
np.where(temp_score > 60, 1, 0)

array([[0, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

## 4 统计运算
统计指标也是我们分析问题的一种方式,常见的指标如下：

|  函数名称   | 描述  |
| :-----:| :----: |
| np.min|计算元素的最小值| 
| np.max|计算元素的最大值|   
| np.median|计算元素的中位数|   
|np.mean|计算元素的均值|   
| np.std|计算元素的标准差|    
| np.var|计算元素的方差|
| np.sum|计算元素的和|
| np.prod|计算元素的积|
| np.argmin|找出最小值的索引|
| np.argmax|找出最大值的索引|

* 注意：里面的参数都有axis指定行或列，详细的axis解释在后文有详细说明，若是在搞不清楚，axis=0或axis=1都试试即可。

## 5 数组排序
* np.sort():指定轴进行排序。默认是使用数组的最后一个轴进行排序。


* np.argsort():返回排序后的下标值。

In [9]:
# 新建一个数组
a = np.random.randint(0,10,size=(3,5))
a

array([[9, 0, 1, 1, 7],
       [3, 4, 2, 6, 3],
       [9, 2, 7, 3, 5]])

In [10]:
# 轴的顺序为[0,1],np.sort默认是按照最后一个轴进行排序
# 因为最后一个轴是1，所以就是将最里面的元素进行排序
b = np.sort(a)
b

array([[0, 1, 1, 7, 9],
       [2, 3, 3, 4, 6],
       [2, 3, 5, 7, 9]])

In [11]:
# axis=0，表示跨行进行排序，即对每一列的值进行排序
c = np.sort(a,axis=0)
c

array([[3, 0, 1, 1, 3],
       [9, 2, 2, 3, 5],
       [9, 4, 7, 6, 7]])